version: '3'
services:
  web:
    container_name: loncolcms1_web
    image: nginx:latest
    restart: always
    environment: 
      - TRACE_API_URL: http://192.168.1.11:8400
    ports:
      - 8400:80
    volumes: 
      - ./build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
