gitlab:
    image: gitlab/gitlab-ce:11.3.6-ce.0
    restart: always
    hostname: '192.168.1.11'
    environment:
        GITLAB_OMNIBUS_CONFIG: |
            external_url 'https://192.168.1.11:8443'
            nginx['redirect_http_to_https'] = true
            letsencrypt['enable'] = false
            nginx['ssl_certificate'] = "/etc/gitlab/nginx.pem"
            nginx['ssl_certificate_key'] = "/etc/gitlab/nginx.key"
    ports:
        - 8443:8443
    volumes:
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab
        - ./config:/etc/gitlab