version: "3"
services:
  node:
    container_name: loncol_node_1
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    ports:
      - "8080:3000"
    command: node server.js
